### imports

In [110]:
from random import random
import numpy as np
import torch
import time

### Comments

In [13]:
"""
this is a docstring
can be used for multiple lines
"""

def myFunction():
    """
    this is a docstring for a function
    """

print(myFunction.__doc__)


    this is a docstring for a function
    


### Variables

In [17]:
# integer

x= 10

#float

y=2.0

#string

ticker='BTC_USDT'

#boolean

isPriceHigherThan10k = True

In [18]:
# Operators and Expressions

z = x + y

print(z)

z = x%y
print(z)

12.0
0.0


### List and Arrays

In [77]:
# more flexible and different data types
pricesList = [2.34,3.51,1.21,7.99,10.01,'BTC']
print(pricesList)

# store one type of data and faster for heavy computations
pricesArray = np.array([2.34,3.51,1.21,7.99,10.01])
print(pricesArray)

# for Neural Networks
pricesTensor = torch.Tensor(pricesArray)
print(pricesTensor)

# append to list
pricesList.append(5.42)
print(f"pricesList {pricesList}")

# call items from list
print('last item : ' ,pricesList[-1])
print("second last from array : ",pricesArray[-2])
print(f'first three items: {pricesList[:3]}')
print(f'last three items: {pricesList[-3:]}')
print(f'all but last items: {pricesList[:-1]}')

[2.34, 3.51, 1.21, 7.99, 10.01, 'BTC']
[ 2.34  3.51  1.21  7.99 10.01]
tensor([ 4.3400,  5.5100,  3.2100,  9.9900, 12.0100])
pricesList [2.34, 3.51, 1.21, 7.99, 10.01, 'BTC', 5.42]
last item :  5.42
second last from array :  7.99
first three items: [2.34, 3.51, 1.21]
last three items: [10.01, 'BTC', 5.42]
all but last items: [2.34, 3.51, 1.21, 7.99, 10.01, 'BTC']


In [86]:
listLength = len(pricesList)
arrayLength = len(pricesTensor)  
print(f'length of list: {listLength}',f'\nlength of tensor array: {arrayLength}')

## Shape and Reshape

openPrices = np.array([2.34,3.51,1.21,7.99,10.01])
closePrices = np.array([4.34,6.51,2.21,14.99,21.01])

prices_array = np.array([openPrices,closePrices])
print(f'prices_array: {prices_array}')
print(f'prices_array shape: {prices_array.shape}')
print(f'prices_array reshaped: {prices_array.reshape(5,2)}')

print(f'prices_array flatten: {prices_array.flatten()}')

length of list: 7 
length of tensor array: 5
prices_array: [[ 2.34  3.51  1.21  7.99 10.01]
 [ 4.34  6.51  2.21 14.99 21.01]]
prices_array shape: (2, 5)
prices_array reshaped: [[ 2.34  3.51]
 [ 1.21  7.99]
 [10.01  4.34]
 [ 6.51  2.21]
 [14.99 21.01]]
prices_array flatten: [ 2.34  3.51  1.21  7.99 10.01  4.34  6.51  2.21 14.99 21.01]


### Dictionaries

In [106]:
# creating dictionary
stock_dict1 = {'ticker':'BTC','open':2.34,'close':4.34,'name':'Bitcoin','current_price':10.01}
stock_dict2 = {'ticker':'XRP','open':0.34,'close':1.42,'name':'Ripple','current_price':5.01}
stock_dict3 = {'ticker':'ETH','open':1.34,'close':2.42,'name':'Ethereum','current_price':7.01}
stock_dict4= {'ticker':'LTS','open':0.34,'close':1.42,'name':'Lite','current_price':5.01}

print(f'stock_dict1: {stock_dict1}')
print(f'stock_dict2: {stock_dict2}')

print(f'stock_dict1 ticker: {stock_dict1["ticker"]}')
print(f'stock_dict1 ticker: {stock_dict1["current_price"]}')

my_stocks = [stock_dict1,stock_dict2,stock_dict3,stock_dict4]

print(f'my_stocks: {my_stocks}')

print('first stock ticker ', my_stocks[0]['ticker'])

# storing lists in dictionary

my_prices_dict = {'open':openPrices,'close':closePrices}

print(f'my_prices_dict: open-prices {my_prices_dict["open"]}')
print(f'last open price is :  {my_prices_dict["open"][-1]}')


stock_dict1: {'ticker': 'BTC', 'open': 2.34, 'close': 4.34, 'name': 'Bitcoin', 'current_price': 10.01}
stock_dict2: {'ticker': 'XRP', 'open': 0.34, 'close': 1.42, 'name': 'Ripple', 'current_price': 5.01}
stock_dict1 ticker: BTC
stock_dict1 ticker: 10.01
my_stocks: [{'ticker': 'BTC', 'open': 2.34, 'close': 4.34, 'name': 'Bitcoin', 'current_price': 10.01}, {'ticker': 'XRP', 'open': 0.34, 'close': 1.42, 'name': 'Ripple', 'current_price': 5.01}, {'ticker': 'ETH', 'open': 1.34, 'close': 2.42, 'name': 'Ethereum', 'current_price': 7.01}]
first stock ticker  BTC
my_prices_dict: open-prices [ 2.34  3.51  1.21  7.99 10.01]
last open price is :  10.01


### If Statements

In [104]:
i = 1
if(i==1):
    print('True')
else:
    print('i is : ', i)

# and, or, in, not
    
tech_stocks = ['AAPL','GOOG','FB','MSFT','TSLA','AMZN',"BTC"]

if('AAPL' in tech_stocks):
        print('AAPL is in tech_stocks')

if('AAPL' in tech_stocks and 'GOOG' in tech_stocks):
        print('AAPL and GOOG are in tech_stocks')

if('XRP' not in tech_stocks):
        print('XRP is not in tech_stocks')

if ('XRP' not in tech_stocks or 'BTC' not in tech_stocks):
        print('XRP or BTC are not in tech_stocks')


if ('XRP' not in tech_stocks and 'PAAL' not in tech_stocks):
        print('XRP and PAAL are not in tech_stocks')

# tenary operator
        
buy_signal = 'BUY' if my_stocks[0]["open"] < my_stocks[0]["close"] and  my_stocks[0]["current_price"] < my_stocks[0]["close"]  else 'HODL'
print(f'buy_signal: {buy_signal}')



True
AAPL is in tech_stocks
AAPL and GOOG are in tech_stocks
XRP is not in tech_stocks
XRP or BTC are not in tech_stocks
XRP and PAAL are not in tech_stocks
buy_signal: HODL


### Loops

In [ ]:
# for loop
for stock in my_stocks:
    print(stock['ticker'],stock['current_price'])

total_value = 0
for stock in my_stocks:
    total_value += stock['current_price']

print(f'total_value: {total_value}')

# while loop

# if not defined i will set whatever the loop sets it
# and wont run again
while(i < 3):
    print(i)
    i += 1
    time.sleep(1)


stock_names=[]
j = 0
while(j < len(my_stocks)):
    stock_names.append(my_stocks[j]['name'])
    j += 1

print("stock_names : ",stock_names)


k = 0
while(k < len(my_stocks)):
    if(my_stocks[k]['ticker'] == 'ETH'):
        print('ETH is in the list with the index of : ',k)
        break
    k += 1

print(my_stocks[2])

# get the stocks with the current price 6 > 
prices_above_6 = []
for stock in my_stocks:
    print('looking through the stock prices')
    if(stock['current_price'] <= 6):
        continue
    prices_above_6.append(stock['current_price'])

print(f'prices_above_6: {prices_above_6}')

# Functions

In [144]:
def add_prices(price1,price2):
    return price1 + price2

print(f'added: {add_prices(2,3)}')

added: 5


# Classes

In [147]:
# create class

class StockTracker():
    def __init__(self,name,price):
        self.name = name
        self.price = price

    def _random_generator(self):
        return random()
    
    def multiply_by_random(self,number:int):
        return number * self._random_generator()
    

# class instance
    
stock_btc = StockTracker('BTC',10000)
stock_eth = StockTracker('ETH',500)

        

In [150]:
print(f'stock_btc: {stock_btc.multiply_by_random(10)}')
print(f'stock_eth name: {stock_eth.name}')

stock_btc: 6.056704596138067
stock_eth name: ETH
